version: '3.8'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "10051:10051"
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    networks:
      zabbix-network:
        ipv4_address: ${ZABBIX_SERVER_IP}

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    restart: always
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHP_TZ: Asia/Tokyo
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    networks:
      zabbix-network:
        ipv4_address: ${ZABBIX_WEB_IP}

  zabbix-mysql:
    image: mysql:8.0
    container_name: zabbix-mysql
    restart: always
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      zabbix-network:
        ipv4_address: ${ZABBIX_MYSQL_IP}

networks:
  zabbix-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${ZABBIX_SUBNET}

volumes:
  zabbix_server_data:
  mysql_data:

